changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - github-actions[bot]
      - dependabot[bot]
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
