use std::io::{self, IsTerminal as _, Write as _};

use imagegen_bridge::core::{BridgeError, ErrorCode, ImagePayload, ImageResponse};
use serde::Serialize;

use crate::args::OutputMode;

pub(crate) struct Output {
    mode: OutputMode,
    quiet: bool,
    allow_inline: bool,
}

impl Output {
    pub(crate) const fn new(mode: OutputMode, quiet: bool, allow_inline: bool) -> Self {
        Self {
            mode,
            quiet,
            allow_inline,
        }
    }

    pub(crate) fn value(&self, value: &impl Serialize) -> Result<(), BridgeError> {
        let mut stdout = io::stdout().lock();
        match self.mode {
            OutputMode::Json | OutputMode::Plain => serde_json::to_writer(&mut stdout, value),
            OutputMode::Human => serde_json::to_writer_pretty(&mut stdout, value),
        }
        .map_err(|_| output_error("could not encode command output"))?;
        writeln!(stdout).map_err(|_| output_error("could not write command output"))
    }

    pub(crate) fn response(&self, response: &ImageResponse) -> Result<(), BridgeError> {
        if self.mode == OutputMode::Json {
            if should_refuse_inline(
                io::stdout().is_terminal(),
                self.allow_inline,
                response
                    .data
                    .iter()
                    .any(|image| matches!(image.payload, ImagePayload::B64Json { .. })),
            ) {
                return Err(BridgeError::new(
                    ErrorCode::InvalidRequest,
                    "refusing to print base64 image data to a terminal; use artifact/url output, redirect stdout, or pass --allow-inline",
                ));
            }
            return self.value(response);
        }
        if self.quiet {
            return Ok(());
        }
        let mut stdout = io::stdout().lock();
        if self.mode == OutputMode::Human {
            writeln!(
                stdout,
                "{} image(s) generated by {} ({})",
                response.data.len(),
                response.provider,
                response.id
            )
            .map_err(|_| output_error("could not write command output"))?;
        }
        for image in &response.data {
            let payload = match &image.payload {
                ImagePayload::Artifact { id, name } => name.as_deref().unwrap_or(id),
                ImagePayload::Url { url } => url,
                ImagePayload::Metadata => "metadata",
                ImagePayload::B64Json { .. } => {
                    "base64 omitted (use --json with redirected stdout)"
                }
            };
            writeln!(
                stdout,
                "{payload}\t{}x{}\t{}\t{} bytes\t{}",
                image.width, image.height, image.format, image.bytes, image.sha256
            )
            .map_err(|_| output_error("could not write command output"))?;
        }
        if let Some(revised) = response.revised_prompt.as_deref()
            && self.mode == OutputMode::Human
        {
            writeln!(stdout, "revised prompt: {revised}")
                .map_err(|_| output_error("could not write command output"))?;
        }
        Ok(())
    }

    pub(crate) fn status(&self, message: &str) -> Result<(), BridgeError> {
        if self.quiet {
            return Ok(());
        }
        let mut stderr = io::stderr().lock();
        if self.mode == OutputMode::Json {
            serde_json::to_writer(&mut stderr, &serde_json::json!({"status": message}))
                .map_err(|_| output_error("could not encode command status"))?;
            writeln!(stderr).map_err(|_| output_error("could not write command status"))
        } else {
            writeln!(stderr, "{message}")
                .map_err(|_| output_error("could not write command status"))
        }
    }

    pub(crate) fn error(&self, error: &BridgeError) {
        let mut stderr = io::stderr().lock();
        if self.mode == OutputMode::Json {
            let _ = serde_json::to_writer(&mut stderr, error);
            let _ = writeln!(stderr);
        } else {
            let _ = writeln!(stderr, "error: {}", error.message);
            if let Some(provider) = error.provider.as_deref() {
                let _ = writeln!(stderr, "provider: {provider}");
            }
        }
    }

    pub(crate) fn internal_error(&self, message: &str) {
        self.error(&BridgeError::new(ErrorCode::Internal, message));
    }
}

pub(crate) const fn exit_code(code: ErrorCode) -> u8 {
    match code {
        ErrorCode::InvalidRequest | ErrorCode::Configuration | ErrorCode::IdempotencyConflict => 2,
        ErrorCode::Authentication | ErrorCode::PermissionDenied | ErrorCode::SafetyRejected => 3,
        ErrorCode::Input | ErrorCode::Artifact | ErrorCode::Session => 4,
        ErrorCode::RateLimited | ErrorCode::Overloaded => 5,
        ErrorCode::Upstream | ErrorCode::Protocol | ErrorCode::UnsupportedCapability => 6,
        ErrorCode::Timeout => 124,
        ErrorCode::Cancelled => 130,
        ErrorCode::Internal => 70,
    }
}

fn output_error(message: &str) -> BridgeError {
    BridgeError::new(ErrorCode::Internal, message)
}

const fn should_refuse_inline(
    stdout_is_terminal: bool,
    allow_inline: bool,
    has_inline_image: bool,
) -> bool {
    stdout_is_terminal && !allow_inline && has_inline_image
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exit_codes_are_stable_and_nonzero() {
        assert_eq!(exit_code(ErrorCode::InvalidRequest), 2);
        assert_eq!(exit_code(ErrorCode::Authentication), 3);
        assert_eq!(exit_code(ErrorCode::Timeout), 124);
        assert_eq!(exit_code(ErrorCode::Cancelled), 130);
    }

    #[test]
    fn inline_images_require_explicit_terminal_opt_in() {
        assert!(should_refuse_inline(true, false, true));
        assert!(!should_refuse_inline(false, false, true));
        assert!(!should_refuse_inline(true, true, true));
        assert!(!should_refuse_inline(true, false, false));
    }
}
