use std::{
    borrow::Cow,
    io::{self, IsTerminal as _, Write as _},
    path::{Path, PathBuf},
};

use imagegen_bridge::core::{BridgeError, ErrorCode, ImagePayload, ImageResponse};
use serde::Serialize;

use crate::{args::OutputMode, presentation::resolve_local_file};

pub(crate) struct Output {
    mode: OutputMode,
    quiet: bool,
    allow_inline: bool,
    local_artifact_paths: bool,
}

impl Output {
    pub(crate) const fn new(
        mode: OutputMode,
        quiet: bool,
        allow_inline: bool,
        local_artifact_paths: bool,
    ) -> Self {
        Self {
            mode,
            quiet,
            allow_inline,
            local_artifact_paths,
        }
    }

    pub(crate) const fn is_human(&self) -> bool {
        matches!(self.mode, OutputMode::Human)
    }

    pub(crate) const fn is_machine(&self) -> bool {
        !self.is_human()
    }

    pub(crate) const fn is_json(&self) -> bool {
        matches!(self.mode, OutputMode::Json)
    }

    pub(crate) const fn is_plain(&self) -> bool {
        matches!(self.mode, OutputMode::Plain)
    }

    pub(crate) fn value(&self, value: &impl Serialize) -> Result<(), BridgeError> {
        let mut stdout = io::stdout().lock();
        match self.mode {
            OutputMode::Json | OutputMode::Plain => serde_json::to_writer(&mut stdout, value),
            OutputMode::Human => serde_json::to_writer_pretty(&mut stdout, value),
        }
        .map_err(|_| output_error("could not encode command output"))?;
        writeln!(stdout).map_err(|_| output_error("could not write command output"))
    }

    pub(crate) fn response(
        &self,
        response: &ImageResponse,
        artifact_root: &Path,
        max_artifact_bytes: u64,
    ) -> Result<(), BridgeError> {
        if self.mode == OutputMode::Json {
            if self.local_artifact_paths {
                return self.value(&local_artifact_result(
                    response,
                    artifact_root,
                    max_artifact_bytes,
                )?);
            }
            if should_refuse_inline(
                io::stdout().is_terminal(),
                self.allow_inline,
                response
                    .data
                    .iter()
                    .any(|image| matches!(image.payload, ImagePayload::B64Json { .. })),
            ) {
                return Err(BridgeError::new(
                    ErrorCode::InvalidRequest,
                    "refusing to print base64 image data to a terminal; use artifact/url output, redirect stdout, or pass --allow-inline",
                ));
            }
            return self.value(response);
        }
        if self.quiet {
            return Ok(());
        }
        let mut stdout = io::stdout().lock();
        if self.mode == OutputMode::Human {
            writeln!(
                stdout,
                "{} image(s) generated by {} ({})",
                response.data.len(),
                terminal_safe(&response.provider),
                terminal_safe(&response.id)
            )
            .map_err(|_| output_error("could not write command output"))?;
        }
        for image in &response.data {
            let payload = match &image.payload {
                ImagePayload::Artifact { id, name } => name.as_deref().unwrap_or(id),
                ImagePayload::Url { url } => url,
                ImagePayload::Metadata => "metadata",
                ImagePayload::B64Json { .. } => {
                    "base64 omitted (use --json with redirected stdout)"
                }
            };
            let payload = terminal_safe(payload);
            writeln!(
                stdout,
                "{}\t{payload}\t{}x{}\t{}\t{} bytes\t{}",
                image.index, image.width, image.height, image.format, image.bytes, image.sha256
            )
            .map_err(|_| output_error("could not write command output"))?;
            if let Some(metadata_name) = image.metadata_name.as_deref() {
                writeln!(
                    stdout,
                    "metadata[{}]\t{}",
                    image.index,
                    terminal_safe(metadata_name)
                )
                .map_err(|_| output_error("could not write command output"))?;
            }
        }
        for failure in &response.failures {
            writeln!(
                stdout,
                "failed[{}]\t{:?}\t{} ms\t{}",
                failure.index,
                failure.error.code,
                failure.generation_ms,
                terminal_safe(&failure.error.message)
            )
            .map_err(|_| output_error("could not write command output"))?;
        }
        if response.attempts.len() > 1 {
            for attempt in &response.attempts {
                writeln!(
                    stdout,
                    "provider attempt\t{}\t{:?}\t{} ms{}",
                    terminal_safe(&attempt.provider),
                    attempt.outcome,
                    attempt.duration_ms,
                    attempt
                        .error_code
                        .map_or_else(String::new, |code| format!("\t{code:?}"))
                )
                .map_err(|_| output_error("could not write command output"))?;
            }
        }
        if let Some(revised) = response.revised_prompt.as_deref()
            && self.mode == OutputMode::Human
        {
            writeln!(stdout, "revised prompt: {}", terminal_safe(revised))
                .map_err(|_| output_error("could not write command output"))?;
        }
        Ok(())
    }

    pub(crate) fn status(&self, message: &str) -> Result<(), BridgeError> {
        if self.quiet {
            return Ok(());
        }
        let mut stderr = io::stderr().lock();
        if self.mode == OutputMode::Json {
            serde_json::to_writer(&mut stderr, &serde_json::json!({"status": message}))
                .map_err(|_| output_error("could not encode command status"))?;
            writeln!(stderr).map_err(|_| output_error("could not write command status"))
        } else {
            writeln!(stderr, "{}", terminal_safe(message))
                .map_err(|_| output_error("could not write command status"))
        }
    }

    pub(crate) fn error(&self, error: &BridgeError) {
        let mut stderr = io::stderr().lock();
        if self.mode == OutputMode::Json {
            let _ = serde_json::to_writer(&mut stderr, error);
            let _ = writeln!(stderr);
        } else {
            let _ = writeln!(stderr, "error: {}", terminal_safe(&error.message));
            if let Some(provider) = error.provider.as_deref() {
                let _ = writeln!(stderr, "provider: {}", terminal_safe(provider));
            }
            if error.code == ErrorCode::SafetyRejected {
                let _ = writeln!(
                    stderr,
                    "recovery: revise the prompt or input images; retrying the unchanged request will not help"
                );
            }
        }
    }

    pub(crate) fn internal_error(&self, message: &str) {
        self.error(&BridgeError::new(ErrorCode::Internal, message));
    }
}

fn terminal_safe(value: &str) -> Cow<'_, str> {
    if !value.chars().any(char::is_control) {
        return Cow::Borrowed(value);
    }
    let mut safe = String::with_capacity(value.len());
    for character in value.chars() {
        if character.is_control() {
            safe.extend(character.escape_default());
        } else {
            safe.push(character);
        }
    }
    Cow::Owned(safe)
}

#[derive(Debug, Serialize)]
struct LocalArtifactResult<'a> {
    response: &'a ImageResponse,
    artifacts: Vec<LocalArtifact>,
}

#[derive(Debug, Serialize)]
struct LocalArtifact {
    index: u8,
    path: PathBuf,
    #[serde(skip_serializing_if = "Option::is_none")]
    metadata_path: Option<PathBuf>,
}

fn local_artifact_result<'a>(
    response: &'a ImageResponse,
    artifact_root: &Path,
    max_artifact_bytes: u64,
) -> Result<LocalArtifactResult<'a>, BridgeError> {
    let artifacts = response
        .data
        .iter()
        .map(|image| {
            let ImagePayload::Artifact {
                name: Some(name), ..
            } = &image.payload
            else {
                return Err(BridgeError::new(
                    ErrorCode::InvalidRequest,
                    "--local-artifact-paths requires named artifact output",
                ));
            };
            let path =
                resolve_local_file(artifact_root, name, max_artifact_bytes, Some(&image.sha256))?;
            let metadata_path = image
                .metadata_name
                .as_deref()
                .map(|name| resolve_local_file(artifact_root, name, max_artifact_bytes, None))
                .transpose()?;
            Ok(LocalArtifact {
                index: image.index,
                path,
                metadata_path,
            })
        })
        .collect::<Result<Vec<_>, BridgeError>>()?;
    Ok(LocalArtifactResult {
        response,
        artifacts,
    })
}

pub(crate) const fn exit_code(code: ErrorCode) -> u8 {
    match code {
        ErrorCode::InvalidRequest | ErrorCode::Configuration | ErrorCode::IdempotencyConflict => 2,
        ErrorCode::Authentication | ErrorCode::PermissionDenied | ErrorCode::SafetyRejected => 3,
        ErrorCode::Input | ErrorCode::Artifact | ErrorCode::Session => 4,
        ErrorCode::RateLimited | ErrorCode::Overloaded => 5,
        ErrorCode::Upstream | ErrorCode::Protocol | ErrorCode::UnsupportedCapability => 6,
        ErrorCode::Timeout => 124,
        ErrorCode::Cancelled => 130,
        ErrorCode::Internal => 70,
    }
}

fn output_error(message: &str) -> BridgeError {
    BridgeError::new(ErrorCode::Internal, message)
}

const fn should_refuse_inline(
    stdout_is_terminal: bool,
    allow_inline: bool,
    has_inline_image: bool,
) -> bool {
    stdout_is_terminal && !allow_inline && has_inline_image
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used)]

    use sha2::Digest as _;

    use super::*;

    #[test]
    fn local_artifact_result_contains_only_verified_absolute_paths() {
        let directory = tempfile::tempdir().expect("temporary directory");
        let root = directory.path().join("artifacts");
        std::fs::create_dir_all(root.join("agent")).expect("artifact directory");
        std::fs::write(root.join("agent/result.png"), b"verified image fixture")
            .expect("artifact fixture");
        std::fs::write(root.join("agent/result.png.json"), b"{}").expect("metadata fixture");
        let mut response: ImageResponse =
            serde_json::from_str(include_str!("../../../fixtures/sdk/image-response.json"))
                .expect("response fixture");
        response.data[0].payload = ImagePayload::Artifact {
            id: "artifact-1".to_owned(),
            name: Some("agent/result.png".to_owned()),
        };
        response.data[0].sha256 =
            base16ct::lower::encode_string(&sha2::Sha256::digest(b"verified image fixture"));
        response.data[0].metadata_name = Some("agent/result.png.json".to_owned());

        let result = local_artifact_result(&response, &root, 1024).expect("local result");
        let value = serde_json::to_value(result).expect("serialize local result");
        assert_eq!(value["response"]["id"], response.id);
        assert_eq!(value["artifacts"][0]["index"], 0);
        assert_eq!(
            value["artifacts"][0]["path"],
            std::fs::canonicalize(root.join("agent/result.png"))
                .expect("canonical artifact")
                .to_string_lossy()
                .as_ref()
        );
        assert_eq!(
            value["artifacts"][0]["metadata_path"],
            std::fs::canonicalize(root.join("agent/result.png.json"))
                .expect("canonical metadata")
                .to_string_lossy()
                .as_ref()
        );

        std::fs::write(root.join("agent/result.png"), b"replaced")
            .expect("replace artifact fixture");
        let error =
            local_artifact_result(&response, &root, 1024).expect_err("changed artifact must fail");
        assert_eq!(error.code, ErrorCode::Artifact);
        assert!(error.message.contains("verified checksum"));
    }

    #[test]
    fn local_artifact_result_rejects_non_artifact_payloads() {
        let response: ImageResponse =
            serde_json::from_str(include_str!("../../../fixtures/sdk/image-response.json"))
                .expect("response fixture");
        let directory = tempfile::tempdir().expect("temporary directory");
        let error = local_artifact_result(&response, directory.path(), 1024)
            .expect_err("base64 output must fail");
        assert_eq!(error.code, ErrorCode::InvalidRequest);
        assert!(error.message.contains("named artifact output"));
    }

    #[test]
    fn exit_codes_are_stable_and_nonzero() {
        assert_eq!(exit_code(ErrorCode::InvalidRequest), 2);
        assert_eq!(exit_code(ErrorCode::Authentication), 3);
        assert_eq!(exit_code(ErrorCode::Timeout), 124);
        assert_eq!(exit_code(ErrorCode::Cancelled), 130);
    }

    #[test]
    fn inline_images_require_explicit_terminal_opt_in() {
        assert!(should_refuse_inline(true, false, true));
        assert!(!should_refuse_inline(false, false, true));
        assert!(!should_refuse_inline(true, true, true));
        assert!(!should_refuse_inline(true, false, false));
    }

    #[test]
    fn safety_rejection_exits_as_a_caller_action_error() {
        let error = BridgeError::safety_rejected("blocked");
        assert_eq!(exit_code(error.code), 3);
        assert_eq!(error.details["recovery"], "revise_prompt_or_inputs");
    }

    #[test]
    fn terminal_text_escapes_all_unicode_control_characters() {
        let unsafe_text = "before\u{1b}[31m\nforged\rline\u{7f}\u{85}after";
        let safe = terminal_safe(unsafe_text);
        assert_eq!(safe, "before\\u{1b}[31m\\nforged\\rline\\u{7f}\\u{85}after");
        assert!(!safe.chars().any(char::is_control));
        assert!(matches!(
            terminal_safe("ordinary"),
            Cow::Borrowed("ordinary")
        ));
    }
}
